### ISSUE TITLE
Release mod on CurseForge

### ISSUE THREAD

**Issue by amazingcoco** [yooksi/daylight#18]

**Comment by matshou** [comment]
Description for CurseForge mod page:

> Are you tired of guessing what time of day it is? Don't have resources to make a clock or it's not precise enough for you? Were you recently killed by mobs seconds away from your make-shift house and dropped  all your precious goods because your time estimation was slightly off? Well, your dog days are over.
>
> Team Yoco proudly presents Daylight, precise and flexible visual indicator of current game time located in the upper right corner of your screen. With seamless and graceful animation that displays solar and lunar changes you will always be one step ahead of time.
>
> Daylight will make your playing experience much better knowing you don't have to think about time. It's size and frame is delicate so you'll never even know it's there. Just joking, you will cause it's awesome! In matter of fact, it's better then wolfs... I mean clocks.
>
> Team Yoco

**Comment by matshou** [comment]
Daylight has been submitted to [CurseForge](https://www.curseforge.com/minecraft/mc-mods/daylight), waiting for approval.

**Comment by matshou** [comment]
> The status of the file daylight-1.15.2-0.1.1.jar (Daylight) has been changed to Approved 
`5/19/2020 1:23 PM`
