### ISSUE TITLE
Snow background

### ISSUE THREAD

**Issue by amazingcoco** [yooksi/daylight#7]

**Comment by zixi-nox** [comment]
![](https://static.vecteezy.com/system/resources/previews/000/123/097/large_2x/snowy-pine-tree-landscape-vector.jpg)

**Comment by amazingcoco** [comment]
![](https://static.vecteezy.com/system/resources/previews/000/089/389/large_2x/free-snow-covered-rolling-hills-vector.jpg)

**Comment by amazingcoco** [comment]
![](https://static.vecteezy.com/system/resources/previews/000/132/166/large_2x/free-christmas-vector-landscape.jpg)

**Comment by amazingcoco** [comment]
![](https://static.vecteezy.com/system/resources/previews/000/690/462/non_2x/snowscape-nature-scene-icon-vector.jpg)

**Comment by amazingcoco** [comment]
![](https://static.vecteezy.com/system/resources/previews/000/456/626/non_2x/ice-landscape-mountain-and-ice-vector.jpg)

**Comment by amazingcoco** [comment]
![](https://static.vecteezy.com/system/resources/previews/000/266/264/non_2x/flat-simple-winter-forest-landscape-vector-background.jpg)

**Comment by amazingcoco** [comment]
![](https://static.vecteezy.com/system/resources/previews/000/266/885/large_2x/abstract-winter-sepia-landscape-background-illustration-vector.jpg)

**Comment by zixi-nox** [comment]
https://www.vecteezy.com/vector-art/266106-winter-forrest-illustration

**Comment by amazingcoco** [comment]
![](https://static.vecteezy.com/system/resources/previews/000/266/106/large_2x/vector-winter-forrest-illustration.jpg)
